default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

  username:
  password:

development:
  <<: *default
  database: board_and_roll_development

test:
  <<: *default
  database: board_and_roll_test

production:
  <<: *default
  database: board_and_roll_production
