user1=User.create(name: "Kamil", surname: "Filipowski", city: "lolopolo", email: "lolopolo@gmail.com", password: "lolopolo", confirmed_at: Time.now)
user2=User.create(name: "Maciej", surname: "Michalik", city: "lolopolo", email: "test@gmail.com", password: "lolopolo", confirmed_at: Time.now)
event1=Event.create(name: "D&D", description: "We are all playing D&D", city: "Lodz", address: "Pietryna 217", start_t: DateTime.parse("09/08/2016 17:00"), end_t: DateTime.parse("09/08/2016 22:00"))
event2=Event.create(name: "Grzybobranie", description: "We are all playing Grzybobranie", city: "Lodz", address: "Rojna 2", start_t: DateTime.parse("12/08/2016 10:00"), end_t: DateTime.parse("13/08/2016 10:00"))
event3=Event.create(name: "Pandemia", description: "We are all playing Pandemia", city: "Lodz", address: "Pietryna 272", start_t: DateTime.parse("14/09/2016 14:00"), end_t: DateTime.parse("14/09/2016 18:00"))
UserEvent.create(user_id: user1.id, event_id: event1.id, owner: true)
UserEvent.create(user_id: user1.id, event_id: event2.id, owner: true)
UserEvent.create(user_id: user2.id, event_id: event3.id, owner: true)
